"""Tests against HDF5 Group autotest files.

These files come from the HDF5 library's own test suite and cover a wide range
of HDF5 features: superblock versions, B-tree variants, data types, filters,
dimension scales, and edge cases. Many of these are intentionally corrupted or
use exotic features (family drivers, virtual datasets, onion VFD, etc.) that
are not relevant for cloud-native HDF5 reading.

Result summary (HDF5 2.0.0): 248 passed, 183 xfailed.

Top failure categories:
  - 44 I/O error (truncated/split files, family driver members)
  - 36 Not an HDF5 file (multi/onion VFD fragments)
  - 12 object header data too short
  -  8 Virtual dataset layout (class 3)
  -  7 dtype V != S/O/c (string/reference/complex mapped to void)
  -  7 Unsupported datatype class (2, 11, 15)
  -  6 Unsupported object header version 0
  -  6 External raw data files
  -  6 length must be >= 1 (zero-size void dtype)
"""

import pytest

from .conftest import h5py_comparison, hdf5_group_examples, resolve_folder

# ---------------------------------------------------------------------------
# Known failures — full relative paths, sorted alphabetically
# ---------------------------------------------------------------------------

xfail_files: set[str] = {
    "hl/test/testfiles/test_ld.h5",
    "hl/test/testfiles/test_table_be.h5",
    "hl/test/testfiles/test_table_cray.h5",
    "hl/test/testfiles/test_table_le.h5",
    "test/testfiles/bad_compound.h5",
    "test/testfiles/bad_offset.h5",
    "test/testfiles/be_data.h5",
    "test/testfiles/btree_idx_1_6.h5",
    "test/testfiles/charsets.h5",
    "test/testfiles/corrupt_stab_msg.h5",
    "test/testfiles/cve_2020_10810.h5",
    "test/testfiles/cve_2020_10812.h5",
    "test/testfiles/deflate.h5",
    "test/testfiles/family_v16-000000.h5",
    "test/testfiles/family_v16-000001.h5",
    "test/testfiles/family_v16-000002.h5",
    "test/testfiles/family_v16-000003.h5",
    "test/testfiles/filespace_1_6.h5",
    "test/testfiles/fill_old.h5",
    "test/testfiles/h5fc_ext1_f.h5",
    "test/testfiles/h5fc_ext1_i.h5",
    "test/testfiles/h5fc_ext2_if.h5",
    "test/testfiles/h5fc_ext2_sf.h5",
    "test/testfiles/h5fc_ext3_isf.h5",
    "test/testfiles/h5fc_ext_none.h5",
    "test/testfiles/le_data.h5",
    "test/testfiles/multi_file_v16-r.h5",
    "test/testfiles/multi_file_v16-s.h5",
    "test/testfiles/tarrold.h5",
    "test/testfiles/tbogus.h5",
    "test/testfiles/test_filters_be.h5",
    "test/testfiles/test_filters_le.h5",
    "test/testfiles/th5s.h5",
    "test/testfiles/tmisc38a.h5",
    "test/testfiles/tmisc38b.h5",
    "test/testfiles/tmtimeo.h5",
    "tools/test/testfiles/3790_infinite_loop.h5",
    "tools/test/testfiles/charsets.h5",
    "tools/test/testfiles/compounds_array_vlen1.h5",
    "tools/test/testfiles/compounds_array_vlen2.h5",
    "tools/test/testfiles/family_file00000.h5",
    "tools/test/testfiles/family_file00001.h5",
    "tools/test/testfiles/family_file00002.h5",
    "tools/test/testfiles/family_file00003.h5",
    "tools/test/testfiles/family_file00004.h5",
    "tools/test/testfiles/family_file00005.h5",
    "tools/test/testfiles/family_file00006.h5",
    "tools/test/testfiles/family_file00007.h5",
    "tools/test/testfiles/family_file00008.h5",
    "tools/test/testfiles/family_file00009.h5",
    "tools/test/testfiles/family_file00010.h5",
    "tools/test/testfiles/family_file00011.h5",
    "tools/test/testfiles/family_file00012.h5",
    "tools/test/testfiles/family_file00013.h5",
    "tools/test/testfiles/family_file00014.h5",
    "tools/test/testfiles/family_file00015.h5",
    "tools/test/testfiles/family_file00016.h5",
    "tools/test/testfiles/family_file00017.h5",
    "tools/test/testfiles/h5clear_fsm_persist_greater.h5",
    "tools/test/testfiles/h5clear_fsm_persist_less.h5",
    "tools/test/testfiles/h5clear_fsm_persist_noclose.h5",
    "tools/test/testfiles/h5clear_fsm_persist_user_equal.h5",
    "tools/test/testfiles/h5clear_fsm_persist_user_greater.h5",
    "tools/test/testfiles/h5clear_fsm_persist_user_less.h5",
    "tools/test/testfiles/h5clear_log_v3.h5",
    "tools/test/testfiles/h5clear_mdc_image.h5",
    "tools/test/testfiles/h5clear_sec2_v3.h5",
    "tools/test/testfiles/h5clear_status_noclose.h5",
    "tools/test/testfiles/h5copytst.h5",
    "tools/test/testfiles/h5copytst_new.h5",
    "tools/test/testfiles/h5diff_strings1.h5",
    "tools/test/testfiles/h5diff_strings2.h5",
    "tools/test/testfiles/h5diff_types.h5",
    "tools/test/testfiles/h5fc_edge_v3.h5",
    "tools/test/testfiles/h5fc_ext1_f.h5",
    "tools/test/testfiles/h5fc_ext1_i.h5",
    "tools/test/testfiles/h5fc_ext1_s.h5",
    "tools/test/testfiles/h5fc_ext2_if.h5",
    "tools/test/testfiles/h5fc_ext2_is.h5",
    "tools/test/testfiles/h5fc_ext2_sf.h5",
    "tools/test/testfiles/h5fc_ext3_isf.h5",
    "tools/test/testfiles/h5fc_ext_none.h5",
    "tools/test/testfiles/h5fc_non_v3.h5",
    "tools/test/testfiles/h5repack_CVE-2018-14460.h5",
    "tools/test/testfiles/h5repack_CVE-2018-17432.h5",
    "tools/test/testfiles/h5repack_filters.h5",
    "tools/test/testfiles/h5repack_fletcher.h5",
    "tools/test/testfiles/h5repack_layout.h5",
    "tools/test/testfiles/h5repack_named_dtypes.h5",
    "tools/test/testfiles/h5repack_nbit.h5",
    "tools/test/testfiles/h5repack_objs.h5",
    "tools/test/testfiles/h5repack_soffset.h5",
    "tools/test/testfiles/h5stat_err_old_fill.h5",
    "tools/test/testfiles/h5stat_err_old_layout.h5",
    "tools/test/testfiles/h5stat_err_refcount.h5",
    "tools/test/testfiles/h5stat_filters.h5",
    "tools/test/testfiles/h5stat_threshold.h5",
    "tools/test/testfiles/h5stat_tsohm.h5",
    "tools/test/testfiles/latest_h5clear_log_v3.h5",
    "tools/test/testfiles/latest_h5clear_sec2_v3.h5",
    "tools/test/testfiles/tCVE_2018_11206_fill_new.h5",
    "tools/test/testfiles/tCVE_2018_11206_fill_old.h5",
    "tools/test/testfiles/tarray1.h5",
    "tools/test/testfiles/tarray2.h5",
    "tools/test/testfiles/tarray3.h5",
    "tools/test/testfiles/tarray4.h5",
    "tools/test/testfiles/tarray5.h5",
    "tools/test/testfiles/tarray6.h5",
    "tools/test/testfiles/tarray7.h5",
    "tools/test/testfiles/tattrreg.h5",
    "tools/test/testfiles/tbfloat16.h5",
    "tools/test/testfiles/tbfloat16_be.h5",
    "tools/test/testfiles/tchar.h5",
    "tools/test/testfiles/tcmpdintarray.h5",
    "tools/test/testfiles/tcmpdints.h5",
    "tools/test/testfiles/tcmpdintsize.h5",
    "tools/test/testfiles/tcomplex.h5",
    "tools/test/testfiles/tcomplex_be.h5",
    "tools/test/testfiles/tcompound.h5",
    "tools/test/testfiles/tcompound_complex.h5",
    "tools/test/testfiles/tcompound_complex2.h5",
    "tools/test/testfiles/tdatareg.h5",
    "tools/test/testfiles/tdset_idx.h5",
    "tools/test/testfiles/tempty.h5",
    "tools/test/testfiles/test_subfiling_precreate_rank_0.h5",
    "tools/test/testfiles/test_subfiling_stripe_sizes.h5",
    "tools/test/testfiles/tfamily00000.h5",
    "tools/test/testfiles/tfamily00001.h5",
    "tools/test/testfiles/tfamily00002.h5",
    "tools/test/testfiles/tfamily00003.h5",
    "tools/test/testfiles/tfamily00004.h5",
    "tools/test/testfiles/tfamily00005.h5",
    "tools/test/testfiles/tfamily00006.h5",
    "tools/test/testfiles/tfamily00007.h5",
    "tools/test/testfiles/tfamily00008.h5",
    "tools/test/testfiles/tfamily00009.h5",
    "tools/test/testfiles/tfamily00010.h5",
    "tools/test/testfiles/tfcontents1.h5",
    "tools/test/testfiles/tfilters.h5",
    "tools/test/testfiles/tfloatsattrs.h5",
    "tools/test/testfiles/tfvalues.h5",
    "tools/test/testfiles/tmulti-b.h5",
    "tools/test/testfiles/tmulti-g.h5",
    "tools/test/testfiles/tmulti-l.h5",
    "tools/test/testfiles/tmulti-o.h5",
    "tools/test/testfiles/tmulti-r.h5",
    "tools/test/testfiles/tmulti-s.h5",
    "tools/test/testfiles/tnamed_dtype_attr.h5",
    "tools/test/testfiles/tnestedcmpddt.h5",
    "tools/test/testfiles/tnestedcomp.h5",
    "tools/test/testfiles/tsaf.h5",
    "tools/test/testfiles/tscalarstring.h5",
    "tools/test/testfiles/tsplit_file-m.h5",
    "tools/test/testfiles/tsplit_file-r.h5",
    "tools/test/testfiles/tstr.h5",
    "tools/test/testfiles/tstr3.h5",
    "tools/test/testfiles/tudlink.h5",
    "tools/test/testfiles/tvldtypes1.h5",
    "tools/test/testfiles/tvldtypes2.h5",
    "tools/test/testfiles/tvldtypes3.h5",
    "tools/test/testfiles/tvldtypes4.h5",
    "tools/test/testfiles/tvldtypes5.h5",
    "tools/test/testfiles/tvlenstr_array.h5",
    "tools/test/testfiles/tvms.h5",
    "tools/test/testfiles/twithub.h5",
    "tools/test/testfiles/twithub513.h5",
    "tools/test/testfiles/vds/1_vds.h5",
    "tools/test/testfiles/vds/2_vds.h5",
    "tools/test/testfiles/vds/3_1_vds.h5",
    "tools/test/testfiles/vds/3_2_vds.h5",
    "tools/test/testfiles/vds/4_vds.h5",
    "tools/test/testfiles/vds/5_vds.h5",
    "tools/test/testfiles/vds/vds-eiger.h5",
    "tools/test/testfiles/vds/vds-percival-unlim-maxmin.h5",
    "tools/test/testfiles/xml/tcompound2.h5",
    "tools/test/testfiles/xml/tdset2.h5",
    "tools/test/testfiles/xml/tenum.h5",
    "tools/test/testfiles/xml/tnodata.h5",
    "tools/test/testfiles/xml/tobjref.h5",
    "tools/test/testfiles/xml/topaque.h5",
    "tools/test/testfiles/xml/tref.h5",
    "tools/test/testfiles/xml/tstring-at.h5",
    "tools/test/testfiles/xml/tstring.h5",
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("rel_path", hdf5_group_examples())
async def test_hdf5_group_file(rel_path):
    if rel_path in xfail_files:
        pytest.xfail("Known failure")
    filepath = str(resolve_folder("tests/data/hdf5-group") / rel_path)
    await h5py_comparison(filepath)
